global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8091']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'loki'
    static_configs:
      - targets: ['loki-query-frontend:3100']

  - job_name: 'django-app'
    static_configs:
      - targets: ['django-app:8000']
    metrics_path: '/django/metrics'
