services:

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
    networks:
      - logging-network
    volumes:
      - minio-data:/data
    restart: unless-stopped
    cpus: "1"
    mem_limit: "1000m"
    labels:
      logging: enabled

  minio-init:
    image: minio/mc
    container_name: minio-init
    networks:
      - logging-network
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minio minio123;
      mc mb -p local/loki;
      mc policy set public local/loki;
      exit 0;
      "

  loki-write:
    image: grafana/loki:3.6.7
    container_name: loki-write
    command: -config.file=/etc/loki/loki.yaml -target=write
    networks:
      - logging-network
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml
    depends_on:
      - minio
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: "300m"

  loki-read:
    image: grafana/loki:3.6.7
    container_name: loki-read
    command: -config.file=/etc/loki/loki.yaml -target=read
    networks:
      - logging-network
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml
    depends_on:
      - loki-write
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: "300m"

  loki-backend:
    image: grafana/loki:3.6.7
    container_name: loki-backend
    command: -config.file=/etc/loki/loki.yaml -target=backend
    networks:
      - logging-network
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml
    depends_on:
      - minio
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: "300m"

  query-scheduler:
    image: grafana/loki:3.6.7
    container_name: query-scheduler
    command: -config.file=/etc/loki/loki.yaml -target=query-scheduler
    networks:
      - logging-network
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: "300m"

  query-frontend:
    image: grafana/loki:3.6.7
    container_name: query-frontend
    command: -config.file=/etc/loki/loki.yaml -target=query-frontend
    networks:
      - logging-network
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml
    ports:
      - "3100:3100"
    depends_on:
      - query-scheduler
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: "300m"

  alloy:
    image: grafana/alloy:v1.13.2
    container_name: alloy
    command: run /etc/alloy/config.river --log.level=debug
    networks:
      - logging-network
    volumes:
      - ./alloy-config.river:/etc/alloy/config.river
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - loki-write
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: "300m"

volumes:
  minio-data:

networks:
  logging-network:
    external: true
    name: logging-network