auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist
    instance_interface_names:
      - eth0
  compactor_grpc_address: loki-backend:9095
  

memberlist:
  join_members:
    - loki-write

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  aws:
    bucketnames: loki
    endpoint: minio:9000
    access_key_id: minio
    secret_access_key: minio123
    s3forcepathstyle: true
    insecure: true

  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache

query_scheduler:
  max_outstanding_requests_per_tenant: 1024

limits_config:
  retention_period: 168h

compactor:
  working_directory: /loki/compactor
  compaction_interval: 5m

ui:
  enabled: true
