apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true

  - name: loki
    type: loki
    uid: loki
    url: http://loki-query-frontend:3100
    access: proxy
    editable: true

  - name: jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger-query:16686
    access: proxy
    editable: true

  - name: pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    url: http://pyroscope-query-frontend:4040
    access: proxy
    editable: true
