{
 "title": "Container Info",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "label_values(container_cpu_usage_seconds_total{name!=''}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name!=\"\"})"
    }
   ]
  },
  {
   "title": "Top CPU",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(3, rate(container_cpu_usage_seconds_total{name!=\"\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top Memory",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "topk(3, container_memory_usage_bytes{name!=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "container" },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{name=\"$container\"}[1m])) / on(name) (container_spec_cpu_quota{name=\"$container\"} / container_spec_cpu_period{name=\"$container\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"$container\"} / container_spec_memory_limit_bytes{name=\"$container\"} * 100"
    }
   ]
  },
  {
   "title": "Memory usage vs limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"$container\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "container_spec_memory_limit_bytes{name=\"$container\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU usage vs limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"$container\"}[1m])",
     "legendFormat": "usage"
    },
    {
     "expr": "container_spec_cpu_quota{name=\"$container\"} / container_spec_cpu_period{name=\"$container\"}",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}