mode: nftables

api_url: ${API_URL}
api_key: ${API_KEY}

disable_ipv6: false
blacklists_ipv4: crowdsec-blacklists
blacklists_ipv6: crowdsec6-blacklists
update_frequency: 10s

deny_action: drop

log_mode: stdout
log_level: info