service:
  extensions: [jaeger_storage]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_storage:
    backends:
      cassandra_store:
        cassandra:
          schema:
            keyspace: jaeger_v1_dc1
          connection:
            servers:
              - scylla
            local_dc: datacenter1
            port: 9042
            consistency: ONE

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: cassandra_store
