service:
  extensions: [jaeger_storage]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_storage:
    backends:
      cassandra_store:
        cassandra:
          schema:
            keyspace: jaeger_v1_dc1
            datacenter: datacenter1
            trace_ttl: 72h
            dependencies_ttl: 1152h
            compaction_window: 2h
            replication_factor: 1
          connection:
            servers:
              - scylla:9042
            tls:
              insecure: true

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: cassandra_store
