services:
  secured-traefik:
    image: traefik:v3.6.9
    container_name: secured-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.bufferingsize=100"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/traefik/logs/access.log"
      - "--accesslog.fields.defaultmode=keep"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--accesslog.fields.headers.names.X-Forwarded-For=keep"
      - "--api.dashboard=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entryPoints.metrics.address=:8091"
      - "--metrics.prometheus.entryPoint=metrics"
      # - "--tracing=true"
      # - "--tracing.otlp=true"
      # - "--tracing.otlp.grpc.insecure=true"
      # - "--tracing.otlp.grpc.endpoint=otel-collector:4317"
      # - "--tracing.serviceName=traefik"
      # - "--tracing.sampleRate=1.0"
      - "--experimental.plugins.crowdsec-bouncer-traefik-plugin.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.crowdsec-bouncer-traefik-plugin.version=v1.6.0"
    ports:
      - "80:80"
      - "8090:8080"
      - "8091:8091"
    networks:
      - traefik-network
      - crowdsec-network
      - metrics-network
      - tracing-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-logs:/traefik/logs
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: "500m"
    labels:
      logging: enabled

  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.8-debian
    container_name: crowdsec
    environment:
      COLLECTIONS: |
        crowdsecurity/traefik
        crowdsecurity/http-cve
        crowdsecurity/sshd
        crowdsecurity/appsec-virtual-patching
        crowdsecurity/appsec-generic-rules
        crowdsecurity/linux
        crowdsecurity/iptables
      BOUNCER_KEY_TRAEFIK: "traefik-secret-key"  # 꼭 바꾸삼
      BOUNCER_KEY_FIREWALL: "firewall-secret-key"  # 꼭 바꾸삼
      CROWDSEC_LAPI_URL: http://127.0.0.1:8080
      API_SERVER_URL: http://127.0.0.1:8080
    volumes:
      - crowdsec-db:/var/lib/crowdsec/data
      - crowdsec-config:/etc/crowdsec
      - ./config/acquis.d:/etc/crowdsec/acquis.d
      - traefik-logs:/var/log/traefik:ro
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    cap_add:
      - SYS_ADMIN
    networks:
      - crowdsec-network
    ports:
      - "8080:8080"
      - "7422:7422"
    restart: unless-stopped
    cpus: "0.3"
    mem_limit: "256m"
    labels:
      logging: enabled
  
  crowdsec-firewall-bouncer:
    image: ghcr.io/shgew/cs-firewall-bouncer-docker:v0.0.34
    container_name: crowdsec-firewall-bouncer
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - no-new-privileges:true
    environment:
      API_URL: "http://127.0.0.1:8080"
      API_KEY: "firewall-secret-key" # 꼭 바꾸삼
    volumes:
      - ./config/crowdsec-firewall-bouncer.yaml:/config/crowdsec-firewall-bouncer.yaml:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  secured-grafana:
    image: grafana/grafana:12.4
    container_name: secured-grafana
    volumes:
      - grafana-data-2:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana:/etc/grafana/dashboards
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - logging-network
      - traefik-network
      - grafana-network
      - tracing-network
      - profiling-network
    cpus: "0.5"
    mem_limit: "1G"
    labels:
      logging: enabled
      traefik.enable: "true"
      traefik.docker.network: "traefik-network"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
      traefik.http.routers.grafana.rule: "PathPrefix(`/`)"
      traefik.http.routers.grafana.entrypoints: "web"
      traefik.http.routers.grafana.middlewares: "crowdsec@docker"
      traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer-traefik-plugin.enabled: true
      traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer-traefik-plugin.crowdseclapikey: "traefik-secret-key" # 꼭 바꾸삼
      traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer-traefik-plugin.crowdseclapischeme: "http"
      traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer-traefik-plugin.crowdseclapihost: "crowdsec:8080"
      traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer-traefik-plugin.crowdsecappsecenabled: "true"
      traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer-traefik-plugin.crowdsecappsechost: "crowdsec:7422"

  crowdsec-web-ui:
    image: ghcr.io/theduffman85/crowdsec-web-ui:2026.5.3
    container_name: crowdsec_web_ui
    ports:
      - "3001:3000"
    environment:
      - CROWDSEC_URL=http://crowdsec:8080
      - CROWDSEC_USER=crowdsec-web-ui # 꼭 바꾸삼 add_user.sh 참고
      - CROWDSEC_PASSWORD=testing # 꼭 바꾸삼
    volumes:
      - ui-data:/app/data
    restart: unless-stopped
    networks:
      - crowdsec-network

volumes:
  ui-data:
  grafana-data-2:
  traefik-logs:
  crowdsec-db:
  crowdsec-config:

networks:
  crowdsec-network:
    external: true
    name: crowdsec-network
  traefik-network:
    external: true
    name: traefik-network
  tracing-network:
    external: true
    name: tracing-network
  metrics-network:
    external: true
    name: metrics-network
  grafana-network:
    external: true
    name: grafana-network
  profiling-network:
    external: true
    name: profiling-network
  logging-network:
    external: true
    name: logging-network
