services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    container_name: cadvisor
    privileged: true
    ports:
      - "8080:8080"
    networks:
      - metrics-network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    cpus: "0.3"
    mem_limit: "250m"
  
  prometheus:
    image: prom/prometheus:v3.10.0
    container_name: prometheus
    ports:
      - "9090:9090"
    user: root
    networks:
      - metrics-network
      - logging-network
      - grafana-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=3GB'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: "1G"

networks:
  metrics-network:
    external: true
    name: metrics-network
  grafana-network:
    external: true
    name: grafana-network
  logging-network:
    external: true
    name: logging-network